baseurl = "/" # Hostname (and path) to the root.
title = "cameronpak" # Site title.
theme = "coder" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

# disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Cameron Pak" # Author's name.
    info = "Web Developer and Friend" # Author's job title or info.
    description = "Cameron Pak's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/profile.jpg" # Contain the path of the optional avatar in the static folder.

    footercontent = "Whoever Finds God Finds Life." # Add footer content

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
# [[params.social]]
#     name = "Github"
#     weight = 1
#     url = "https://github.com/cameronapak/"
# [[params.social]]
#     name = "Twitter"
#     weight = 2
#     url = "https://twitter.com/johndoe/"
# [[params.social]]
#     name = "LinkedIn"
#     weight = 3
#     url = "https://www.linkedin.com/in/johndoe/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/post/"
# [[menu.main]]
#     name = "About"
#     weight = 2
#     url = "/about/"
